source "https://rubygems.org"

gem "mysql2"
gem "glimmer-dsl-libui",'~> 0.7.4'
gem 'win32api'
gem "minitest"
gem 'rubocop', group: 'development'
gem 'rubbish_code', '~> 0.1.0'
gem 'rybish_code', '~> 2.0'